*! _pte_mc_validate_dgp.ado
*! Monte Carlo DGP Validation Module
*!
*! Validates DGP data generated by _pte_mc_dgp for bias assessment.
*! Checks:
*!   - Variable existence (omega0, omega1, omega_true, nt, firm)
*!   - omega1 is non-missing only for treated observations
*!   - Treated observations (nt >= 0) exist
*!   - Returns clear error messages for missing/invalid data

version 14.0
capture program drop _pte_mc_validate_dgp
program define _pte_mc_validate_dgp, rclass
	version 14.0
	
	// ================================================================
	// Syntax definition
	// ----------------------------------------------------------------
	// All parameters are required for DGP validation
	// ================================================================
	syntax , ///
		omega0(varname)    /// counterfactual productivity (control path)
		omega1(varname)    /// actual productivity (treated path)
		nt(varname)        /// time relative to treatment (event time)
		firm(varname)      /// firm identifier
		[omega_true(varname)]  /// true omega (optional, for MC validation)
	
	// ================================================================
	// Task 1: Variable existence check
	// ----------------------------------------------------------------
	// Verify each required DGP variable exists in the dataset.
	// Exit 111 if not found (standard Stata "variable not found").
	// ================================================================
	
	// Check omega0
	capture confirm variable `omega0'
	if _rc != 0 {
		di as error ""
		di as error "_pte_mc_validate_dgp: variable {bf:`omega0'} not found"
		di as error "  omega0 (counterfactual productivity) is required for bias assessment"
		di as error "  ensure _pte_mc_dgp has been run successfully"
		exit 111
	}
	
	// Check omega1
	capture confirm variable `omega1'
	if _rc != 0 {
		di as error ""
		di as error "_pte_mc_validate_dgp: variable {bf:`omega1'} not found"
		di as error "  omega1 (treated productivity) is required for bias assessment"
		di as error "  ensure _pte_mc_dgp has been run successfully"
		exit 111
	}
	
	// Check nt (event time)
	capture confirm variable `nt'
	if _rc != 0 {
		di as error ""
		di as error "_pte_mc_validate_dgp: variable {bf:`nt'} not found"
		di as error "  nt (event time relative to treatment) is required"
		di as error "  ensure _pte_mc_dgp has been run successfully"
		exit 111
	}
	
	// Check firm identifier
	capture confirm variable `firm'
	if _rc != 0 {
		di as error ""
		di as error "_pte_mc_validate_dgp: variable {bf:`firm'} not found"
		di as error "  firm identifier is required for panel structure"
		di as error "  ensure _pte_mc_dgp has been run successfully"
		exit 111
	}
	
	// Check omega_true if specified
	if "`omega_true'" != "" {
		capture confirm variable `omega_true'
		if _rc != 0 {
			di as error ""
			di as error "_pte_mc_validate_dgp: variable {bf:`omega_true'} not found"
			di as error "  omega_true (true productivity) was specified but not found"
			exit 111
		}
	}
	
	// ================================================================
	// Task 2: Numeric type validation
	// ----------------------------------------------------------------
	// Ensure all DGP variables are numeric
	// ================================================================
	foreach var in `omega0' `omega1' `nt' {
		capture confirm numeric variable `var'
		if _rc != 0 {
			di as error ""
			di as error "_pte_mc_validate_dgp: variable {bf:`var'} is not numeric"
			di as error "  DGP variables must be numeric for bias calculation"
			exit 109
		}
	}
	
	if "`omega_true'" != "" {
		capture confirm numeric variable `omega_true'
		if _rc != 0 {
			di as error ""
			di as error "_pte_mc_validate_dgp: variable {bf:`omega_true'} is not numeric"
			exit 109
		}
	}

	// ================================================================
	// Task 2b: Validate realized productivity consistency
	// ----------------------------------------------------------------
	// omega_true is the realized productivity path in the Monte Carlo DGP:
	// treated post-treatment observations use omega1, all other
	// observations use omega0. When omega_true() is provided, enforce this
	// contract before downstream bias calculations use the data.
	// ================================================================
	if "`omega_true'" != "" {
		qui count if `nt' >= 0 & `omega1' != . & ///
			(missing(`omega_true') | `omega_true' != `omega1')
		local n_omega_true_post_mismatch = r(N)

		if `n_omega_true_post_mismatch' > 0 {
			di as error ""
			di as error "_pte_mc_validate_dgp: omega_true inconsistent on treated post-treatment observations"
			di as error "  found `n_omega_true_post_mismatch' observations with nt >= 0 and omega1 != omega_true"
			di as error "  realized productivity must equal omega1 on treated post-treatment rows"
			exit 2000
		}

		qui count if !(`nt' >= 0 & `omega1' != .) & ///
			(missing(`omega_true') | `omega_true' != `omega0')
		local n_omega_true_base_mismatch = r(N)

		if `n_omega_true_base_mismatch' > 0 {
			di as error ""
			di as error "_pte_mc_validate_dgp: omega_true inconsistent on untreated or pre-treatment observations"
			di as error "  found `n_omega_true_base_mismatch' observations where omega_true != omega0"
			di as error "  realized productivity must equal omega0 outside treated post-treatment rows"
			exit 2000
		}
	}
	
	// ================================================================
	// Task 3: Validate treated observations exist (nt >= 0)
	// ----------------------------------------------------------------
	// Check that there are observations in the post-treatment period
	// ================================================================
	qui count if `nt' >= 0
	local n_post = r(N)
	
	if `n_post' == 0 {
		di as error ""
		di as error "_pte_mc_validate_dgp: no post-treatment observations found"
		di as error "  expected observations with `nt' >= 0"
		di as error "  check that treatment timing is correctly specified"
		exit 2000
	}
	
	// ================================================================
	// Task 4: Validate omega1 pattern for treated observations
	// ----------------------------------------------------------------
	// omega1 should be non-missing only for treated observations
	// (those with nt >= 0 in the treatment group)
	// ================================================================
	qui count if `nt' >= 0 & `omega1' != .
	local n_treated_omega1 = r(N)
	
	if `n_treated_omega1' == 0 {
		di as error ""
		di as error "_pte_mc_validate_dgp: no treated observations with omega1"
		di as error "  expected non-missing omega1 for treated firms (nt >= 0)"
		di as error "  check DGP simulation output"
		exit 2000
	}
	
	// ================================================================
	// Task 5: Validate omega0 completeness for treated observations
	// ----------------------------------------------------------------
	// Every treated post observation with omega1 must also have omega0
	// so ATT = omega1 - omega0 is defined on the full treated sample.
	// ================================================================
	qui count if `nt' >= 0 & `omega1' != . & missing(`omega0')
	local n_missing_omega0 = r(N)
	
	if `n_missing_omega0' > 0 {
		di as error ""
		di as error "_pte_mc_validate_dgp: treated observations missing omega0"
		di as error "  found `n_missing_omega0' treated post-treatment observations with omega1 but missing omega0"
		di as error "  bias assessment requires both counterfactual (omega0)"
		di as error "  and actual (omega1) productivity for every treated observation"
		exit 2000
	}
	
	qui count if `nt' >= 0 & `omega0' != . & `omega1' != .
	local n_both = r(N)
	
	if `n_both' == 0 {
		di as error ""
		di as error "_pte_mc_validate_dgp: no observations with both omega0 and omega1"
		di as error "  bias assessment requires both counterfactual (omega0)"
		di as error "  and actual (omega1) productivity for treated observations"
		exit 2000
	}
	
	// ================================================================
	// Task 6: Count observations by event time
	// ----------------------------------------------------------------
	// Report observation counts for nt = 0, 1, 2, 3 (standard horizons)
	// ================================================================
	local n_nt0 = 0
	local n_nt1 = 0
	local n_nt2 = 0
	local n_nt3 = 0
	
	qui count if `nt' == 0 & `omega1' != .
	local n_nt0 = r(N)

	if `n_nt0' == 0 {
		di as error ""
		di as error "_pte_mc_validate_dgp: no treatment-year observations found"
		di as error "  expected at least one treated observation with `nt' == 0"
		di as error "  validation requires the instantaneous effect horizon"
		exit 2000
	}
	
	qui count if `nt' == 1 & `omega1' != .
	local n_nt1 = r(N)
	
	qui count if `nt' == 2 & `omega1' != .
	local n_nt2 = r(N)
	
	qui count if `nt' == 3 & `omega1' != .
	local n_nt3 = r(N)
	
	// ================================================================
	// Task 7: Return validation results
	// ================================================================
	return scalar validation_passed = 1
	return scalar n_post = `n_post'
	return scalar n_treated_omega1 = `n_treated_omega1'
	return scalar n_both = `n_both'
	return scalar n_missing_omega0 = `n_missing_omega0'
	return scalar n_nt0 = `n_nt0'
	return scalar n_nt1 = `n_nt1'
	return scalar n_nt2 = `n_nt2'
	return scalar n_nt3 = `n_nt3'
	
	return local omega0_var "`omega0'"
	return local omega1_var "`omega1'"
	return local nt_var "`nt'"
	return local firm_var "`firm'"
	if "`omega_true'" != "" {
		return local omega_true_var "`omega_true'"
	}
	
end
